/**
 * sendReport Lambda Function
 * ─────────────────────────────────────────────────────────────
 * Fetches analysis from DynamoDB, builds report, and sends it
 * directly to the provided email via AWS SES.
 *
 * Route : POST /send-report
 * Payload: { analysisId, email }
 */

"use strict";

const { DynamoDBClient, GetItemCommand }        = require("@aws-sdk/client-dynamodb");
const { SESClient, SendEmailCommand }           = require("@aws-sdk/client-ses");
const { unmarshall }                            = require("@aws-sdk/util-dynamodb");
const { buildReportText }                       = require("./shared");

const dynamo = new DynamoDBClient({ region: process.env.AWS_REGION || "us-east-1" });
const ses    = new SESClient({ region: process.env.AWS_REGION || "us-east-1" });

const CORS = {
  "Access-Control-Allow-Origin":  "*",
  "Access-Control-Allow-Headers": "Content-Type,Authorization",
  "Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,OPTIONS",
};

exports.handler = async (event) => {
  if (event.requestContext?.http?.method === "OPTIONS")
    return { statusCode: 200, headers: CORS, body: "" };

  try {
    const body = JSON.parse(event.body || "{}");
    const { analysisId, email } = body;

    // Validate inputs
    if (!analysisId || !email)
      return { statusCode: 400, headers: CORS, body: JSON.stringify({ error: "analysisId and email are required." }) };

    // Basic email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email))
      return { statusCode: 400, headers: CORS, body: JSON.stringify({ error: "Invalid email address." }) };

    // Fetch from DynamoDB
    const res = await dynamo.send(new GetItemCommand({
      TableName: process.env.DYNAMODB_TABLE,
      Key:       { analysis_id: { S: analysisId } },
    }));
    if (!res.Item)
      return { statusCode: 404, headers: CORS, body: JSON.stringify({ error: "Analysis not found." }) };

    const analysis = unmarshall(res.Item);
    const text     = buildReportText(analysis);

    // Send email via SES
    if (!process.env.SENDER_EMAIL)
      return { statusCode: 500, headers: CORS, body: JSON.stringify({ error: "SENDER_EMAIL not configured." }) };

    const subject = `Cloud ATS Report for ${analysis.resume_name}`;
    const htmlBody = `
      <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
          <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
            <h2 style="color: #2563eb;">📋 ATS Analysis Report</h2>
            <hr style="border: none; border-top: 2px solid #e5e7eb;">
            <p><strong>Resume:</strong> ${analysis.resume_name}</p>
            <p><strong>Role:</strong> ${analysis.selected_role}</p>
            <p><strong>ATS Score:</strong> <span style="font-size: 24px; color: #10b981; font-weight: bold;">${analysis.score}%</span></p>
            <p><strong>Generated:</strong> ${new Date().toISOString()}</p>
            <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
            <pre style="background: #f3f4f6; padding: 15px; border-radius: 5px; overflow-x: auto;">${text}</pre>
            <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
            <p style="font-size: 12px; color: #6b7280;">This report was generated by Cloud ATS Resume Analyzer.</p>
          </div>
        </body>
      </html>
    `;

    await ses.send(new SendEmailCommand({
      Source: process.env.SENDER_EMAIL,
      Destination: {
        ToAddresses: [email],
      },
      Message: {
        Subject: { Data: subject },
        Body: {
          Html: { Data: htmlBody },
          Text: { Data: text },
        },
      },
    }));

    console.log("sendReport sent email to:", email);

    return {
      statusCode: 200,
      headers:    CORS,
      body:       JSON.stringify({
        success: true,
        message: `Report sent to ${email}. Check your inbox!`,
        email,
        analysisId,
      }),
    };
  } catch (err) {
    console.error("sendReport error:", err);
    return { statusCode: 500, headers: CORS, body: JSON.stringify({ error: "Failed to send report." }) };
  }
};
