"use strict";

const fs = require("fs/promises");
const path = require("path");
const pdfParseModule = require("pdf-parse");
const mammoth = require("mammoth");

const pdfParse = pdfParseModule.default || pdfParseModule;

function toUtf8(buffer) {
  return Buffer.isBuffer(buffer) ? buffer.toString("utf-8") : String(buffer || "");
}

async function streamToBuffer(stream) {
  const chunks = [];
  for await (const chunk of stream) {
    chunks.push(Buffer.from(chunk));
  }
  return Buffer.concat(chunks);
}

function normalise(text) {
  return String(text || "").toLowerCase().replace(/[^\w\s.+#]/g, " ").replace(/\s+/g, " ").trim();
}

function keywordPattern(keyword) {
  const tokens = normalise(keyword).split(" ").filter(Boolean).map((token) => token.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
  if (!tokens.length) return null;
  return new RegExp(`(^|\\s)${tokens.join("\\s+")}($|\\s)`, "i");
}

function matchKeywords(text, keywords) {
  const found = [];
  const missing = [];
  for (const keyword of keywords) {
    const regex = keywordPattern(keyword);
    if (regex && regex.test(text)) found.push(keyword); else missing.push(keyword);
  }
  return { found, missing };
}

function generalTips(score) {
  if (score >= 80) return [
    "Great ATS compatibility! Tailor the resume further for each job posting.",
    "Keep bullet points results-oriented (quantify achievements).",
    "Ensure consistent formatting and no spelling errors.",
  ];
  if (score >= 50) return [
    "Add more role-relevant keywords naturally in your experience section.",
    "Use a single-column layout for better ATS parsing.",
    "Replace generic phrases with specific technical accomplishments.",
  ];
  return [
    "Your resume needs significant keyword optimisation for this role.",
    "Add a dedicated Skills section listing the missing keywords.",
    "Build 1-2 projects showcasing the missing technologies.",
    "Use action verbs: Built, Developed, Designed, Optimised, Deployed.",
  ];
}

function extractEmail(text) {
  const match = String(text || "").match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);
  return match ? match[0].replace(/[).,;:]+$/, "") : "";
}

async function extractTextFromBuffer(buffer, fileName = "", contentType = "") {
  const ext = path.extname(fileName).toLowerCase();
  const mime = String(contentType || "").toLowerCase();

  if (ext === ".pdf" || mime.includes("pdf")) {
    const parsed = await pdfParse(buffer);
    return parsed.text || "";
  }

  if (ext === ".docx" || mime.includes("wordprocessingml") || mime.includes("msword")) {
    const parsed = await mammoth.extractRawText({ buffer });
    return parsed.value || "";
  }

  return toUtf8(buffer);
}

async function extractTextFromFile(filePath) {
  const buffer = await fs.readFile(filePath);
  return extractTextFromBuffer(buffer, filePath, "");
}

function buildReportText(a) {
  const div = "=".repeat(55);
  const line = "-".repeat(55);
  const found = Array.isArray(a.found_keywords) ? a.found_keywords : Array.isArray(a.foundKeywords) ? a.foundKeywords : JSON.parse(a.found_keywords || "[]");
  const missing = Array.isArray(a.missing_keywords) ? a.missing_keywords : Array.isArray(a.missingKeywords) ? a.missingKeywords : JSON.parse(a.missing_keywords || "[]");
  const sugg = Array.isArray(a.suggestions) ? a.suggestions : JSON.parse(a.suggestions || "[]");
  const tips = Array.isArray(a.tips) ? a.tips : JSON.parse(a.tips || "[]");
  const resumeName = a.resume_name || a.resumeName || "resume";
  const selectedRole = a.selected_role || a.selectedRole || "Unknown role";
  const score = a.score ?? 0;
  const createdAt = a.created_at || a.createdAt || new Date().toISOString();
  const analysisId = a.analysis_id || a.analysisId || "unknown";
  const extractedEmail = a.extracted_email || a.extractedEmail || "Not found";

  return [
    div,
    "       CLOUD ATS RESUME ANALYZER — REPORT",
    div,
    "",
    `Resume      : ${resumeName}`,
    `Target Role : ${selectedRole}`,
    `ATS Score   : ${score}%`,
    `Generated   : ${createdAt}`,
    `Analysis ID : ${analysisId}`,
    `Email       : ${extractedEmail}`,
    "",
    div, "  FOUND KEYWORDS", line,
    found.length ? found.map((k) => `  ✔  ${k}`).join("\n") : "  None found.",
    "",
    div, "  MISSING KEYWORDS", line,
    missing.length ? missing.map((k) => `  ✘  ${k}`).join("\n") : "  All keywords matched!",
    "",
    div, "  IMPROVEMENT SUGGESTIONS", line,
    sugg.length ? sugg.map((s, i) => `  ${i + 1}. ${s}`).join("\n") : "  No suggestions — great job!",
    "",
    div, "  GENERAL RESUME TIPS", line,
    tips.map((t, i) => `  ${i + 1}. ${t}`).join("\n"),
    "",
    div,
    "  Generated by Cloud ATS Resume Analyzer",
    "  Powered by AWS Lambda + DynamoDB + S3 + SNS",
    div,
  ].join("\n");
}

module.exports = {
  buildReportText,
  extractEmail,
  extractTextFromBuffer,
  extractTextFromFile,
  generalTips,
  matchKeywords,
  normalise,
  streamToBuffer,
};